const DummyDataItems = [
    {
      id: 1,
      name: "Item 1",
      category: "Category 1",
      price: "1000.00",
      supplier: "Supplier 1",
      description: "Description for Item 1",
      quantity: 100,
      reorder: 20,
      manufacture_date: "2023-01-01",
      expire_date: "2024-01-01",
      image: "Bed.jpg",
    },  
    {
      id: 2,
      name: "Item 2",
      category: "Category 2",
      price: "1500.00",
      supplier: "Supplier 2",
      description: "Description for Item 2",
      quantity: 200,
      reorder: 30,
      manufacture_date: "2023-02-01",
      expire_date: "2024-02-01",
      image: "Bowl.jpg", 
    },
    {
      id: 3,
      name: "Item 3",
      category: "Category 1",
      price: "20,000.00",
      supplier: "Supplier 1",
      description: "Description for Item 3",
      quantity: 150,
      reorder: 25,
      manufacture_date: "2023-03-01",
      expire_date: "2024-03-01",
      image: "belt.jpg", 
    },

    {
        id: 4,
        name: "Item 4",
        category: "Category 2",
        price: "500.00",
        supplier: "Supplier 2",
        description: "Description for Item 4",
        quantity: 50,
        reorder: 10,
        manufacture_date: "2023-04-01",
        expire_date: "2024-04-01",
        image: "Food2.jpg",
      },
      {
        id: 5,
        name: "Item 5",
        category: "Category 1",
        price: "3000.00",
        supplier: "Supplier 1",
        description: "Description for Item 5",
        quantity: 80,
        reorder: 15,
        manufacture_date: "2023-05-01",
        expire_date: "2024-05-01",
        image: "Toothpaste.jpg",
      },

      {
        id: 6,
        name: "Item 6",
        category: "Category 2",
        price: "1200.00",
        supplier: "Supplier 2",
        description: "Description for Item 6",
        quantity: 90,
        reorder: 18,
        manufacture_date: "2023-06-01",
        expire_date: "2024-06-01",
        image: "item2.png", 
      },
      {
        id: 7,
        name: "Item 7",
        category: "Category 1",
        price: "2500.00",
        supplier: "Supplier 1",
        description: "Description for Item 7",
        quantity: 120,
        reorder: 30,
        manufacture_date: "2023-07-01",
        expire_date: "2024-07-01",
        image: "toy.jpg",
      }, 
  ];
  
  export default DummyDataItems;
  