
const DummyDataAdmission = [
    {
    _id: "1",
    first_name: "John",
    last_name: "Doe",
    contact_no: "1234567890",
    weight: "20Kg",
    diagnosis: "Fever",
    shelter_type: "S",
    special_notes: "Needs medication",
    shelter_no: "A001",
    status: "Admitted",
    },
    {
    _id: "2",
    first_name: "Jane",
    last_name: "Smith",
    contact_no: "9876543210",
    weight: "15Kg",
    diagnosis: "Injury",
    shelter_type: "M",
    special_notes: "Requires surgery",
    shelter_no: "B002",
    status: "Admitted",
    },
    {
    _id: "3",
    first_name: "Michael",
    last_name: "Johnson",
    contact_no: "2345678901",
    weight: "12Kg",
    diagnosis: "Skin infection",
    shelter_type: "S",
    special_notes: "Needs regular bathing",
    shelter_no: "A003",
    status: "Admitted",
    },
    {
    _id: "4",
    first_name: "Emily",
    last_name: "Brown",
    contact_no: "8901234567",
    weight: "18Kg",
    diagnosis: "Allergy",
    shelter_type: "L",
    special_notes: "Avoid certain foods",
    shelter_no: "C004",
    status: "Admitted",
    },
    {
    _id: "5",
    first_name: "David",
    last_name: "Wilson",
    contact_no: "3456789012",
    weight: "25Kg",
    diagnosis: "Broken leg",
    shelter_type: "M",
    special_notes: "Requires cast",
    shelter_no: "B005",
    status: "Admitted",
    },
    {
    _id: "6",
    first_name: "Sophia",
    last_name: "Thomas",
    contact_no: "6789012345",
    weight: "8Kg",
    diagnosis: "Malnutrition",
    shelter_type: "S",
    special_notes: "Requires nutritional supplements",
    shelter_no: "A006",
    status: "Admitted",
    },
    {
    _id: "7",
    first_name: "Oliver",
    last_name: "Martinez",
    contact_no: "9012345678",
    weight: "10Kg",
    diagnosis: "Eye infection",
    shelter_type: "L",
    special_notes: "Requires eye drops",
    shelter_no: "C007",
    status: "Admitted",
    },
    {
    _id: "8",
    first_name: "Emma",
    last_name: "Johnson",
    contact_no: "4567890123",
    weight: "16Kg",
    diagnosis: "Fractured paw",
    shelter_type: "M",
    special_notes: "Needs splint",
    shelter_no: "B008",
    status: "Admitted",
    },
    // Add more admission objects as needed...
    ];
    
    export default DummyDataAdmission;