const DummyDataPayment = [
    {
        _id: 1,
        pay_services: "Service A",
        pay_total: 1000.00,
        pay_cashierName: "John Doe",
        pay_date: "2023-01-01",
        pay_owner: "Jane Smith",
        pay_pet: "Tom",
      },
      {
        _id: 2,
        pay_services: "Service B", 
        pay_total: 1200.00,
        pay_cashierName: "Alice Johnson",
        pay_date: "2023-02-02",
        pay_owner: "Bob Brown",
        pay_pet: "Blacky",
      },
      {
        _id: 3,
        pay_services: "Service C",
        pay_total: 800.00,
        pay_cashierName: "Sarah Davis",
        pay_date: "2023-03-03",
        pay_owner: "Michael Wilson",
        pay_pet: "Buddy",
      },
      {
        _id: 4,
        pay_services: "Service D",
        pay_total: 1500.00,
        pay_cashierName: "Emily Thompson",
        pay_date: "2023-03-04",
        pay_owner: "David Johnson",
        pay_pet: "Lucy",
      },
      {
        _id: 5,
        pay_services: "Service E",
        pay_total: 900.00,
        pay_cashierName: "Daniel Anderson",
        pay_date: "2023-03-05",
        pay_owner: "Olivia Martinez",
        pay_pet: "Max",
      },
      {
        _id: 6,
        pay_services: "Service F",
        pay_total: 1100.00,
        pay_cashierName: "Sophia Harris",
        pay_date: "2023-04-06",
        pay_owner: "Ethan Clark",
        pay_pet: "Lola",
      },
      {
        _id: 7,
        pay_services: "Service G",
        pay_total: 950.00,
        pay_cashierName: "Aiden Turner",
        pay_date: "2023-05-07",
        pay_owner: "Mia Lee",
        pay_pet: "Rocky",
      },
      {
        _id: 8,
        pay_services: "Service H",
        pay_total: 1300.00,
        pay_cashierName: "Liam Wright",
        pay_date: "2023-06-08",
        pay_owner: "Ava Scott",
        pay_pet: "Milo",
      },
      {
        _id: 9,
        pay_services: "Service I",
        pay_total: 750.00,
        pay_cashierName: "Logan Green",
        pay_date: "2023-07-09",
        pay_owner: "Harper Adams",
        pay_pet: "Coco", 
      },
      {
        _id: 10,
        pay_services: "Service J",
        pay_total: 1600.00,
        pay_cashierName: "Lucas Baker",
        pay_date: "2023-07-10",
        pay_owner: "Evelyn Phillips",
        pay_pet: "Charlie",
      }, 
  ];
    
  export default DummyDataPayment;
  