const DummyDataAnimal = [
    {
      _id: 1,
      owner_ID: "1",
      animal_name: "Fluffy",
      animal_type: "Cat",
      animal_breed: "Persian",
      animal_gender: "Female",
      DOB: "2019-05-01",
      date: "2022-05-01", 
      owner_ID: "John Doe",
    },
    {
      _id: 2,
      owner_ID: "2",
      animal_name: "Buddy",
      animal_type: "Dog",
      animal_breed: "Golden Retriever",
      animal_gender: "Male",
      DOB: "2018-08-15",
      date: "2021-12-10", 
      owner_ID: "Jane Smith",
    }, 
 
    {
      _id: 3,
      owner_ID: "Alice Johnson",
      animal_name: "Max",
      animal_type: "Dog",
      animal_breed: "Labrador Retriever",
      animal_gender: "Male",
      DOB: "2017-04-20",
      date: "2020-11-05",
    },
    {
      _id: 4,
      owner_ID: "Michael Brown",
      animal_name: "Luna",
      animal_type: "Cat",
      animal_breed: "Siamese",
      animal_gender: "Female",
      DOB: "2020-02-10",
      date: "2023-01-20",
    },
    {
      _id: 5,
      owner_ID: "Emily Wilson",
      animal_name: "Rocky",
      animal_type: "Dog",
      animal_breed: "German Shepherd",
      animal_gender: "Male",
      DOB: "2016-09-18",
      date: "2019-07-15",
    }, 

    {
      _id: 6,
      owner_ID: "Sophia Anderson",
      animal_name: "Milo",
      animal_type: "Cat",
      animal_breed: "Maine Coon",
      animal_gender: "Male",
      DOB: "2019-11-07",
      date: "2022-09-30",
    },
    {
      _id: 7,
      owner_ID: "Daniel Wilson",
      animal_name: "Daisy",
      animal_type: "Dog",
      animal_breed: "Beagle",
      animal_gender: "Female",
      DOB: "2017-06-12",
      date: "2021-05-25",
    },
    {
      _id: 8,
      owner_ID: "Olivia Thompson",
      animal_name: "Charlie",
      animal_type: "Dog",
      animal_breed: "Poodle",
      animal_gender: "Male",
      DOB: "2020-03-25",
      date: "2023-04-12",
    },
    {
      _id: 9,
      owner_ID: "William Harris",
      animal_name: "Bella",
      animal_type: "Cat",
      animal_breed: "British Shorthair",
      animal_gender: "Female",
      DOB: "2018-01-05",
      date: "2020-08-17",
    },
    {
      _id: 10,
      owner_ID: "Ava Martinez",
      animal_name: "Max",
      animal_type: "Dog",
      animal_breed: "Boxer",
      animal_gender: "Male",
      DOB: "2016-07-22",
      date: "2019-03-10",
    },
    
  ];
   
  export default DummyDataAnimal;
   