const DummyDataOrders = [
    {
      _id: 1,
      selectedItem: "Product 1",
      selectedItemQty: 2,
      totalPrice: 10000.00,
      paymentMethod: "Cash",
      orderStates: "Pending",
      orderDate: "2021-01-01",
    },
    {
      _id: 2,
      selectedItem: "Product 2",
      selectedItemQty: 1,
      totalPrice: 5000.00,
      paymentMethod: "Credit Card",
      orderStates: "Delivered",
      orderDate: "2021-02-15",
    },
    {
      _id: 3,
      selectedItem: "Product 3",
      selectedItemQty: 3,
      totalPrice: 15000.00,
      paymentMethod: "PayPal",
      orderStates: "Processing",
      orderDate: "2021-03-10",
    },
    {
      _id: 4,
      selectedItem: "Product 4",
      selectedItemQty: 1,
      totalPrice: 7500.00,
      paymentMethod: "Cash",
      orderStates: "Cancelled",
      orderDate: "2021-04-05",
    },
    {
      _id: 5,
      selectedItem: "Product 5",
      selectedItemQty: 2,
      totalPrice: 10000.00,
      paymentMethod: "Credit Card",
      orderStates: "Delivered",
      orderDate: "2021-05-20",
    },
    {
      _id: 6,
      selectedItem: "Product 6",
      selectedItemQty: 1,
      totalPrice: 5000.00,
      paymentMethod: "Cash",
      orderStates: "Pending",
      orderDate: "2021-06-15",
    },
    {
      _id: 7,
      selectedItem: "Product 7",
      selectedItemQty: 4,
      totalPrice: 20000.00,
      paymentMethod: "Credit Card",
      orderStates: "Processing",
      orderDate: "2021-07-25",
    },
    {
      _id: 8,
      selectedItem: "Product 8",
      selectedItemQty: 2,
      totalPrice: 10000.00,
      paymentMethod: "PayPal",
      orderStates: "Delivered",
      orderDate: "2021-08-10",
    },
    {
      _id: 9,
      selectedItem: "Product 9",
      selectedItemQty: 3,
      totalPrice: 15000.00,
      paymentMethod: "Cash",
      orderStates: "Cancelled",
      orderDate: "2021-09-05",
    },
    {
      _id: 10,
      selectedItem: "Product 10",
      selectedItemQty: 1,
      totalPrice: 5000.00,
      paymentMethod: "Credit Card",
      orderStates: "Delivered",
      orderDate: "2021-10-20",
    },
  ];
  
  export default DummyDataOrders;
  